import {
  auth, provider, onAuthStateChanged, signInWithPopup, signOut,
  db, orgRef, orgCollection, orgDoc, doc, getDoc, getDocs, setDoc,
  addDoc, updateDoc, deleteDoc, writeBatch, serverTimestamp, ADMIN_EMAIL
} from './firebase-init.js';

const $ = (s) => document.querySelector(s);
const $$ = (s) => Array.from(document.querySelectorAll(s));
const state = { user:null, profile:null, view:'dashboard', periodId:null, data:{}, dataLoaded:false, loading:false };
const ROLES = {admin:'مدير النظام', manager:'مدير', accountant:'محاسب', operator:'موظف قراءات', viewer:'مشاهد', resident:'ساكن', pending:'بانتظار الموافقة'};
const COLLECTIONS = ['buildings','units','subscribers','meters','periods','readings','sources','energyReadings','costs','payments','ledger','members'];
const money = v => `${new Intl.NumberFormat('ar-PS',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))} ₪`;
const num = v => Number(v||0);
const fmt = (v,d=2) => new Intl.NumberFormat('ar-PS',{maximumFractionDigits:d}).format(Number(v||0));
const dateNow = () => new Date().toISOString().slice(0,10);
const safe = v => String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmtDate = v => v ? String(v).slice(0,10).split('-').reverse().join('/') : '—';
const roleName = r => ROLES[r] || r || '—';

function toast(msg,type='success'){const e=$('#toast');if(!e)return;e.textContent=msg;e.className='toast '+(type==='error'?'error':'');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.className='toast hidden',3000);}
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false');}
function closeModal(){ $('#modal').classList.add('hidden'); $('#modal').setAttribute('aria-hidden','true'); $('#modalBody').innerHTML=''; }
function can(...roles){return roles.includes(state.profile?.role);}
function setTitle(title,subtitle){const a=$('#page-title'),b=$('#page-subtitle');if(a)a.textContent=title;if(b)b.textContent=subtitle;}
function statusBadge(s){const map={Draft:['مسودة','warn'],Calculated:['محسوبة','info'],Approved:['معتمدة','ok'],Closed:['مغلقة','ok'],Pending:['بانتظار','warn'],Entered:['مدخلة','ok'],Invalid:['غير صالحة','danger']};const x=map[s]||['—','info'];return `<span class="badge ${x[1]}">${x[0]}</span>`;}
function empty(title,text=''){return `<div class="empty"><strong>${safe(title)}</strong><span>${safe(text)}</span></div>`;}
function buildingName(id){return state.data.buildings?.find(x=>x.id===id)?.name||'—';}
function unitForSub(s){return state.data.units?.find(x=>x.id===s.unitId);}
function balanceOf(id){return (state.data.ledger||[]).filter(x=>x.subscriberId===id).reduce((a,x)=>a+num(x.debit)-num(x.credit),0);}
function subscriberRow(s){const u=unitForSub(s);return {...s,unitCode:u?.code||'—',buildingName:buildingName(u?.buildingId),balance:balanceOf(s.id)};}

function upsertLocal(collection,row){const arr=state.data[collection]||[];const i=arr.findIndex(x=>x.id===row.id);if(i>=0)arr[i]={...arr[i],...row};else arr.push(row);state.data[collection]=arr;state.dataLoaded=true;}
function removeLocal(collection,id){state.data[collection]=(state.data[collection]||[]).filter(x=>x.id!==id);state.dataLoaded=true;}

async function loadData(force=false){
  if(state.dataLoaded && !force) return state.data;
  if(state.loading) return state.data;
  state.loading=true;
  const out={};
  try {
    const results=await Promise.all(COLLECTIONS.map(async c=>{
      const snap=await getDocs(orgCollection(c));
      return [c,snap.docs.map(d=>({id:d.id,...d.data()}))];
    }));
    for(const [c,rows] of results) out[c]=rows;
    state.data=out; state.dataLoaded=true; return out;
  } finally { state.loading=false; }
}

async function ensureProfile(){
  const ref=orgDoc('members',state.user.uid); const snap=await getDoc(ref);
  if(snap.exists()) return {id:snap.id,...snap.data()};
  const isAdmin = (state.user.email||'').toLowerCase() === ADMIN_EMAIL.toLowerCase();
  const role=isAdmin?'admin':'pending';
  const data={displayName:state.user.displayName||'مستخدم',email:state.user.email||'',photoURL:state.user.photoURL||'',role,createdAt:serverTimestamp()};
  await setDoc(ref,data); return {id:ref.id,displayName:data.displayName,email:data.email,photoURL:data.photoURL,role};
}
async function ensureSetup(){
  if(state.profile?.role!=='admin')return;
  const meta=await getDoc(doc(orgRef,'meta','setup'));
  if(!meta.exists()) await setDoc(doc(orgRef,'meta','setup'),{initialized:true,ownerUid:state.user.uid,ownerEmail:state.user.email,createdAt:serverTimestamp()});
}

function render(){
  if(!$('#app'))return;
  const fn={dashboard:renderDashboard,subscribers:renderSubscribers,readings:renderReadings,costs:renderCosts,payments:renderPayments,reports:renderReports,settings:renderSettings}[state.view]||renderDashboard;
  fn();
}
async function navigate(view,periodId=null,force=false){
  if(!state.profile || state.profile.role==='pending'){renderPending();return;}
  state.view=view;if(periodId)state.periodId=periodId;
  $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
  await loadData(force); render(); $('#sidebar')?.classList.remove('open');
}

function renderDashboard(){
  setTitle('الرئيسية','كل شيء واضح قدامك — افتح الأسبوع، أدخل القراءات، وخلص.');
  const subs=(state.data.subscribers||[]).filter(s=>s.active!==false); const periods=[...(state.data.periods||[])].sort((a,b)=>String(b.startDate).localeCompare(String(a.startDate))); const latest=periods[0];
  const deb=(state.data.ledger||[]).reduce((a,x)=>a+num(x.debit),0), cred=(state.data.ledger||[]).reduce((a,x)=>a+num(x.credit),0);
  $('#app').innerHTML=`
    <section class="welcome"><div class="kicker">عمارة الأمين • الإدارة اليومية</div><h2>أهلًا ${safe(state.user?.displayName?.split(' ')[0]||'بك')} 👋</h2><p>ما بدنا تعقيد. كل شغلك الأسبوعي موجود في ثلاث خطوات واضحة.</p><div class="welcome-actions"><button class="btn primary" id="startReadings">إدخال قراءات الماء</button><button class="btn light" id="startWeek">فتح أسبوع جديد</button></div><div class="quick-orb"><span>أ</span></div></section>
    <section class="stats"><div class="stat"><div class="stat-label">السكان النشطون</div><div class="stat-value">${fmt(subs.length,0)}</div><div class="stat-foot">مشترك</div></div><div class="stat"><div class="stat-label">الأسبوع الحالي</div><div class="stat-value">${latest?fmtDate(latest.startDate):'—'}</div><div class="stat-foot">${latest?statusBadge(latest.status||'Draft'):'لا يوجد'}</div></div><div class="stat"><div class="stat-label">إجمالي الاستحقاقات</div><div class="stat-value">${money(deb)}</div><div class="stat-foot">من كل الحركات</div></div><div class="stat"><div class="stat-label">إجمالي الدفعات</div><div class="stat-value">${money(cred)}</div><div class="stat-foot">المسجل بالنظام</div></div></section>
    <section class="grid-2"><div class="panel"><div class="panel-head"><div><h2>الطريقة الأسهل للعمل</h2><p>لا تحتاج تعرف مصطلحات تقنية.</p></div></div><div class="steps"><div class="step"><div class="step-num">١</div><div><b>افتح أسبوعًا جديدًا</b><span>النظام ينقل آخر قراءة لكل عداد كقراءة سابقة.</span></div></div><div class="step"><div class="step-num">٢</div><div><b>أدخل القراءة الحالية</b><span>يمكنك تعديل السابقة والحالية في نفس الجدول.</span></div></div><div class="step"><div class="step-num">٣</div><div><b>راجع وصدّر</b><span>الاستهلاك والقيمة تظهر مباشرة وتقدر تنزّل Excel.</span></div></div></div></div><div class="panel"><div class="panel-head"><div><h2>آخر أسبوع</h2><p>${latest?'اضغط عليه للدخول مباشرة.':'ابدأ من زر فتح أسبوع جديد.'}</p></div></div>${latest?`<button class="latest" id="latestWeek"><div class="latest-date">${fmtDate(latest.startDate)}</div><div class="latest-main"><b>${safe(latest.label||'أسبوع')}</b><span>${statusBadge(latest.status||'Draft')}</span></div><span class="arrow">←</span></button>`:empty('لا يوجد أسبوع بعد','افتح أول أسبوع وابدأ الإدخال.')}</div></section>
    <div class="trust"><div class="trust-icon">✓</div><div><b>البيانات في Firebase</b><span>التغييرات تظهر للحسابات المصرح لها، مع حفظ محلي مؤقت للتصفح السريع.</span></div></div>`;
  $('#startReadings').onclick=()=>latest?navigate('readings',latest.id):showPeriodForm(); $('#startWeek').onclick=showPeriodForm; if(latest)$('#latestWeek').onclick=()=>navigate('readings',latest.id);
}

function renderSubscribers(){
  setTitle('السكان','عدّل أي بيانات أساسية بدون ما يضيع تاريخ الحساب.'); const rows=(state.data.subscribers||[]).slice();
  $('#app').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>السكان</h2><p>اضغط على الاسم لفتح كشف الحساب، أو اضغط تعديل لتغيير البيانات.</p></div><div class="panel-actions"><button class="btn soft" id="exportSubs">↓ تصدير Excel</button><button class="btn primary" id="newSub">+ إضافة ساكن</button></div></div><div class="toolbar"><input id="subSearch" class="search" placeholder="ابحث بالاسم أو الكود أو الهاتف…"><span class="muted">${fmt(rows.filter(s=>s.active!==false).length,0)} نشط</span></div><div class="table-wrap"><table class="table"><thead><tr><th>الكود</th><th>الاسم</th><th>البناية</th><th>الوحدة</th><th>الهاتف</th><th>الرصيد</th><th>الحالة</th><th></th></tr></thead><tbody id="subRows">${subscriberRowsHtml(rows)}</tbody></table></div></section>`;
  $('#newSub').onclick=()=>showSubscriberForm(); $('#exportSubs').onclick=()=>exportSubscribers(rows.map(subscriberRow)); $('#subSearch').oninput=e=>$('#subRows').innerHTML=subscriberRowsHtml(rows.filter(s=>[s.name,s.code,s.phone].some(v=>String(v||'').includes(e.target.value))));
}
function subscriberRowsHtml(rows){if(!rows.length)return `<tr><td colspan="8">${empty('لا يوجد سكان','أضف أول ساكن من زر الإضافة.')}</td></tr>`;return rows.map(s=>{const r=subscriberRow(s);return `<tr><td><span class="code">${safe(s.code)}</span></td><td><button class="link" data-account="${s.id}">${safe(s.name)}</button></td><td>${safe(r.buildingName)}</td><td>${safe(r.unitCode)}</td><td>${safe(s.phone||'—')}</td><td class="strong">${money(r.balance)}</td><td>${s.active!==false?'<span class="badge ok">نشط</span>':'<span class="badge warn">مؤرشف</span>'}</td><td><div class="row-actions"><button class="mini" data-edit-sub="${s.id}">تعديل</button>${can('admin','manager')?`<button class="mini red" data-archive-sub="${s.id}">${s.active!==false?'أرشفة':'حذف'}</button>`:''}</div></td></tr>`}).join('');}

function showSubscriberForm(id){
  const s=id?(state.data.subscribers||[]).find(x=>x.id===id):null; const u=s?unitForSub(s):null; const buildings=state.data.buildings||[];
  openModal(`<h2>${s?'تعديل بيانات الساكن':'إضافة ساكن جديد'}</h2><p class="modal-lead">التعديل هنا لا يحذف القراءات أو الدفعات القديمة.</p><div class="form-grid"><div class="field"><label>الاسم</label><input id="fName" value="${safe(s?.name||'')}"></div><div class="field"><label>الكود</label><input id="fCode" value="${safe(s?.code||'')}"></div><div class="field"><label>الهاتف</label><input id="fPhone" value="${safe(s?.phone||'')}"></div><div class="field"><label>البناية</label><select id="fBuilding"><option value="">اختر البناية</option>${buildings.map(b=>`<option value="${b.id}" ${u?.buildingId===b.id?'selected':''}>${safe(b.name)}</option>`).join('')}</select></div><div class="field"><label>رقم الوحدة</label><input id="fUnit" value="${safe(u?.code||'')}"></div><div class="field"><label>الدور</label><input id="fFloor" value="${safe(u?.floor||'')}"></div><div class="field"><label>خدمة الحارس</label><input id="fGuard" type="number" step="0.01" value="${s?.defaultGuardFee??0}"></div><div class="field"><label>تأمين الغاطس</label><input id="fPump" type="number" step="0.01" value="${s?.defaultPumpInsurance??0}"></div><div class="field full"><label>ملاحظات</label><textarea id="fNotes">${safe(s?.notes||'')}</textarea></div></div><div class="actions"><button class="btn primary" id="saveSub">حفظ</button><button class="btn light" id="cancel">إلغاء</button></div>`);
  $('#cancel').onclick=closeModal; $('#saveSub').onclick=async()=>{const name=$('#fName').value.trim(),code=$('#fCode').value.trim();if(!name||!code){toast('اكتب الاسم والكود أولًا','error');return;}if((state.data.subscribers||[]).some(x=>x.code===code&&x.id!==id)){toast('الكود مستخدم بالفعل','error');return;}const buildingId=$('#fBuilding').value;let unitId=u?.id||null;const unitCode=$('#fUnit').value.trim();const floor=$('#fFloor').value.trim();if(buildingId&&unitCode){const found=(state.data.units||[]).find(x=>x.buildingId===buildingId&&x.code===unitCode&&x.id!==u?.id);if(found)unitId=found.id;else{const ur=doc(orgCollection('units'));await setDoc(ur,{buildingId,code:unitCode,unitNumber:unitCode,floor,active:true,createdAt:serverTimestamp()});unitId=ur.id;}}const data={name,code,phone:$('#fPhone').value.trim(),unitId,defaultGuardFee:num($('#fGuard').value),defaultPumpInsurance:num($('#fPump').value),notes:$('#fNotes').value.trim(),active:true};if(s){await updateDoc(orgDoc('subscribers',s.id),{...data,updatedAt:serverTimestamp(),updatedBy:state.user.uid});upsertLocal('subscribers',{id:s.id,...data});toast('تم تعديل بيانات الساكن');}else{const sr=doc(orgCollection('subscribers'));await setDoc(sr,{...data,type:'داخلي',createdAt:serverTimestamp(),createdBy:state.user.uid});const mr=doc(orgCollection('meters'));await setDoc(mr,{meterCode:`W-${code}`,meterType:'مياه',subscriberId:sr.id,unitId,active:true,createdAt:serverTimestamp()});upsertLocal('subscribers',{id:sr.id,...data,type:'داخلي'});upsertLocal('meters',{id:mr.id,meterCode:`W-${code}`,meterType:'مياه',subscriberId:sr.id,unitId,active:true});toast('تمت إضافة الساكن');}closeModal();navigate('subscribers');};
}
async function archiveOrDelete(id){const s=(state.data.subscribers||[]).find(x=>x.id===id);if(!s)return;if(s.active!==false){if(!confirm(`أرشفة ${s.name}؟\nسيبقى كل تاريخه وحسابه موجودًا.`))return;await updateDoc(orgDoc('subscribers',id),{active:false,archivedAt:serverTimestamp(),archivedBy:state.user.uid});upsertLocal('subscribers',{id,active:false});toast('تمت الأرشفة');}else{if((state.data.ledger||[]).some(x=>x.subscriberId===id)){toast('لا يمكن الحذف النهائي لأن لديه حركات مالية. الأرشفة هي الخيار الآمن.','error');return;}if(!confirm(`حذف ${s.name} نهائيًا؟`))return;const batch=writeBatch(db);batch.delete(orgDoc('subscribers',id));for(const m of (state.data.meters||[]).filter(x=>x.subscriberId===id))batch.delete(orgDoc('meters',m.id));await batch.commit();removeLocal('subscribers',id);for(const m of (state.data.meters||[]).filter(x=>x.subscriberId===id))removeLocal('meters',m.id);toast('تم الحذف النهائي');}navigate('subscribers');}

function renderReadings(){
  setTitle('قراءات الماء','هون تدخل قراءة كل ساكن: السابقة ثم الحالية، والباقي يحسبه البرنامج.');
  const periods=[...(state.data.periods||[])].sort((a,b)=>String(b.startDate).localeCompare(String(a.startDate)));
  const selected=state.periodId||periods[0]?.id; state.periodId=selected;
  const help=periods.length
    ? `<div class="reading-how"><div class="reading-how-num">١</div><div><b>اختَر الأسبوع</b><span>افتح الأسبوع المطلوب من الأزرار بالأسفل.</span></div><div class="reading-how-num">٢</div><div><b>اكتب القراءة الحالية</b><span>السابقة موجودة ويمكن تعديلها، والاستهلاك يحسب تلقائيًا.</span></div></div>`
    : `<div class="reading-start"><div class="reading-start-icon">◫</div><div><h2>ما في أسبوع مفتوح لسه</h2><p>أول خطوة هي فتح أسبوع جديد. البرنامج سيجلب آخر قراءة معروفة لكل ساكن كقراءة سابقة، وبعدها تدخل القراءة الحالية لكل عداد.</p><button class="btn primary" id="firstWeek">+ افتح أول أسبوع وابدأ الإدخال</button></div></div>`;
  $('#app').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>قراءات الماء</h2><p>اكتب الأرقام فقط. لا تحتاج تحسب الاستهلاك بنفسك.</p></div><div class="panel-actions"><button class="btn soft" id="exportReading" ${selected?'':'disabled'}>↓ تنزيل Excel</button><button class="btn primary" id="newWeek">+ أسبوع جديد</button></div></div>${help}<div class="period-tabs">${periods.map(p=>`<button class="period-tab ${p.id===selected?'active':''}" data-period="${p.id}"><b>${safe(p.label||'أسبوع')}</b><span>${fmtDate(p.startDate)}</span></button>`).join('')}</div>${selected?readingEditor(selected):''}</section>`;
  $('#newWeek').onclick=showPeriodForm;
  if($('#firstWeek')) $('#firstWeek').onclick=showPeriodForm;
  $$('.period-tab').forEach(x=>x.onclick=()=>navigate('readings',x.dataset.period));
  if(selected && $('#exportReading')) $('#exportReading').onclick=()=>exportPeriod(selected);
  if(selected) bindReadingSave(selected);
}
function readingEditor(pid){const p=(state.data.periods||[]).find(x=>x.id===pid);const rs=(state.data.readings||[]).filter(x=>x.periodId===pid);const rows=rs.map(r=>{const m=(state.data.meters||[]).find(x=>x.id===r.meterId);const s=(state.data.subscribers||[]).find(x=>x.id===m?.subscriberId);return{r,m,s}}).filter(x=>x.s&&x.s.active!==false).sort((a,b)=>String(a.s.code).localeCompare(String(b.s.code)));const completed=rows.filter(x=>x.r.currentReading!=null).length;return `<div class="reading-head"><div><b>${safe(p?.label||'الأسبوع')}</b><div class="muted">${fmtDate(p?.startDate)} — ${fmtDate(p?.endDate)} · ${statusBadge(p?.status||'Draft')}</div></div><div class="reading-summary">${completed} / ${rows.length} قراءة مدخلة</div></div><div class="notice">إذا كانت القراءة السابقة خطأ، عدّلها هنا. لا حاجة للرجوع إلى Excel.</div><div class="table-wrap"><table class="table"><thead><tr><th>الكود</th><th>الساكن</th><th>السابقة</th><th>الحالية</th><th>الاستهلاك</th><th>سعر الكوب</th><th>القيمة</th><th>الحالة</th></tr></thead><tbody>${rows.length?rows.map(x=>{const r=x.r,cons=(r.currentReading!=null&&r.previousReading!=null)?(num(r.currentReading)-num(r.previousReading))/1000:null;const price=r.unitPrice??p?.waterUnitPrice??'';const charge=cons!=null&&price!==''?cons*num(price):null;return `<tr data-reading-row="${r.id}"><td><span class="code">${safe(x.s.code)}</span></td><td>${safe(x.s.name)}</td><td><input class="reading-input prev" type="number" step="0.001" value="${r.previousReading??''}"></td><td><input class="reading-input current" type="number" step="0.001" value="${r.currentReading??''}"></td><td class="cons">${cons==null?'—':fmt(cons,3)}</td><td><input class="reading-input price" type="number" step="0.01" value="${price}"></td><td class="charge">${charge==null?'—':money(charge)}</td><td class="status">${r.currentReading==null?'<span class="badge warn">بانتظار</span>':(cons<0?'<span class="badge danger">تحقق</span>':'<span class="badge ok">جاهزة</span>')}</td></tr>`}).join(''):`<tr><td colspan="8">${empty('لا توجد قراءات لهذا الأسبوع','تأكد أن الأسبوع أُنشئ بعد إضافة السكان.')}</td></tr>`}</tbody></table></div><div class="reading-save"><p>بعد الحفظ، تبقى السابقة والحالية محفوظتين في Firestore.</p><button class="btn primary" id="saveAllReadings">حفظ كل القراءات</button></div>`;}
function bindReadingSave(pid){$$('.reading-input').forEach(inp=>inp.addEventListener('input',()=>{const row=inp.closest('tr');const prev=num(row.querySelector('.prev').value),curV=row.querySelector('.current').value,priceV=row.querySelector('.price').value;const cons=curV===''?'—':fmt((num(curV)-prev)/1000,3);row.querySelector('.cons').textContent=cons;row.querySelector('.charge').textContent=curV!==''&&priceV!==''?money(((num(curV)-prev)/1000)*num(priceV)):'—';row.querySelector('.status').innerHTML=curV===''?'<span class="badge warn">بانتظار</span>':((num(curV)-prev)<0?'<span class="badge danger">تحقق</span>':'<span class="badge ok">جاهزة</span>')}));$('#saveAllReadings').onclick=async()=>{const p=(state.data.periods||[]).find(x=>x.id===pid);const rows=$$('[data-reading-row]');const batch=writeBatch(db);let count=0;for(const row of rows){const id=row.dataset.readingRow,prev=row.querySelector('.prev').value,cur=row.querySelector('.current').value,price=row.querySelector('.price').value;if(cur!==''&&prev!==''&&num(cur)<num(prev)){toast('هناك قراءة حالية أقل من السابقة. راجعها أولًا.','error');return;}const cons=cur!==''&&prev!==''?(num(cur)-num(prev))/1000:null;const charge=cons!=null&&price!==''?cons*num(price):null;batch.update(orgDoc('readings',id),{previousReading:prev===''?null:num(prev),currentReading:cur===''?null:num(cur),consumption:cons,unitPrice:price===''?(p?.waterUnitPrice??null):num(price),chargeAmount:charge,status:cur===''?'Pending':'Entered',updatedAt:serverTimestamp(),updatedBy:state.user.uid});count++;}await batch.commit();for(const row of rows){const id=row.dataset.readingRow,prev=row.querySelector('.prev').value,cur=row.querySelector('.current').value,price=row.querySelector('.price').value;const cons=cur!==''&&prev!==''?(num(cur)-num(prev))/1000:null;const charge=cons!=null&&price!==''?cons*num(price):null;upsertLocal('readings',{id,previousReading:prev===''?null:num(prev),currentReading:cur===''?null:num(cur),consumption:cons,unitPrice:price===''?(p?.waterUnitPrice??null):num(price),chargeAmount:charge,status:cur===''?'Pending':'Entered'});}toast(`تم حفظ ${count} قراءة`);navigate('readings',pid);};}

function showPeriodForm(){openModal(`<h2>فتح أسبوع جديد</h2><p class="modal-lead">النظام سيأخذ آخر قراءة معروفة لكل عداد كقراءة سابقة، وتقدر تعدلها لاحقًا.</p><div class="form-grid"><div class="field"><label>اسم الأسبوع</label><input id="pLabel" value="أسبوع ${fmtDate(dateNow())}"></div><div class="field"><label>من</label><input id="pStart" type="date" value="${dateNow()}"></div><div class="field"><label>إلى</label><input id="pEnd" type="date" value="${dateNow()}"></div><div class="field"><label>سعر الكوب (اختياري)</label><input id="pPrice" type="number" step="0.01" min="0" placeholder="يحسب/يُدخل لاحقًا"></div></div><div class="actions"><button class="btn primary" id="savePeriod">فتح الأسبوع</button><button class="btn light" id="cancelPeriod">إلغاء</button></div>`);$('#cancelPeriod').onclick=closeModal;$('#savePeriod').onclick=async()=>{const label=$('#pLabel').value.trim()||`أسبوع ${fmtDate($('#pStart').value)}`;const ref=doc(orgCollection('periods'));const p={label,startDate:$('#pStart').value,endDate:$('#pEnd').value,status:'Draft',waterUnitPrice:$('#pPrice').value===''?null:num($('#pPrice').value),createdAt:serverTimestamp(),createdBy:state.user.uid};const batch=writeBatch(db);batch.set(ref,p);for(const m of state.data.meters||[]){const prev=[...(state.data.readings||[])].filter(r=>r.meterId===m.id&&r.currentReading!=null).sort((a,b)=>String(b.updatedAt?.seconds||0)-String(a.updatedAt?.seconds||0))[0]?.currentReading??null;batch.set(doc(orgCollection('readings')),{periodId:ref.id,meterId:m.id,previousReading:prev,currentReading:null,consumption:null,unitPrice:p.waterUnitPrice,chargeAmount:null,status:'Pending',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}await batch.commit();upsertLocal('periods',{id:ref.id,...p});for(const m of state.data.meters||[]){const prev=[...(state.data.readings||[])].filter(r=>r.meterId===m.id&&r.currentReading!=null).sort((a,b)=>String(b.updatedAt?.seconds||0)-String(a.updatedAt?.seconds||0))[0]?.currentReading??null;const rr=doc(orgCollection('readings'));/* records were created in batch; local mirror uses generated ids from batch only after commit, so reload once */}state.dataLoaded=false;closeModal();state.periodId=ref.id;toast('تم فتح الأسبوع');await navigate('readings',ref.id,true);};}

function renderCosts(){setTitle('المصاريف','سجّل الكهرباء، السولار، المولد الخارجي، الصيانة والطوارئ.');const costs=state.data.costs||[];$('#app').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>المصاريف</h2><p>كل مصروف له نوع وطريقة تحميل واضحة.</p></div><button class="btn primary" id="addCost">+ إضافة مصروف</button></div><div class="table-wrap"><table class="table"><thead><tr><th>التاريخ</th><th>الفترة</th><th>النوع</th><th>البيان</th><th>المبلغ</th><th>التوزيع</th></tr></thead><tbody>${costs.length?costs.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(c=>`<tr><td>${fmtDate(c.date)}</td><td>${safe((state.data.periods||[]).find(p=>p.id===c.periodId)?.label||'—')}</td><td>${safe(c.type||'—')}</td><td>${safe(c.description||'—')}</td><td class="strong">${money(c.amount)}</td><td>${safe(c.allocation||'—')}</td></tr>`).join(''):`<tr><td colspan="6">${empty('لا توجد مصاريف','أضف أول مصروف من الزر أعلاه.')}</td></tr>`}</tbody></table></div></section>`;$('#addCost').onclick=showCostForm;}
function showCostForm(){const ps=state.data.periods||[];openModal(`<h2>إضافة مصروف</h2><p class="modal-lead">إذا اخترت "على استهلاك المياه" سيدخل ضمن تكلفة سعر الكوب.</p><div class="form-grid"><div class="field"><label>التاريخ</label><input id="cDate" type="date" value="${dateNow()}"></div><div class="field"><label>الأسبوع</label><select id="cPeriod"><option value="">بدون أسبوع</option>${ps.map(p=>`<option value="${p.id}">${safe(p.label)}</option>`).join('')}</select></div><div class="field"><label>النوع</label><select id="cType"><option>مولد خارجي</option><option>نقل</option><option>وقود</option><option>صيانة</option><option>طوارئ</option><option>مصروف آخر</option><option>مساهمة/خصم</option></select></div><div class="field"><label>المبلغ</label><input id="cAmount" type="number" step="0.01" min="0"></div><div class="field"><label>طريقة التوزيع</label><select id="cAlloc"><option value="WATER_CONSUMPTION">على استهلاك المياه</option><option value="EACH_SUBSCRIBER">بالتساوي على السكان</option><option value="NONE">لا يتم تحميله</option></select></div><div class="field"><label>المورد</label><input id="cVendor"></div><div class="field full"><label>البيان</label><input id="cDesc" placeholder="مثال: استئجار مولد لليلة واحدة"></div></div><div class="actions"><button class="btn primary" id="saveCost">حفظ المصروف</button><button class="btn light" id="cancelCost">إلغاء</button></div>`);$('#cancelCost').onclick=closeModal;$('#saveCost').onclick=async()=>{const ref=doc(orgCollection('costs'));const row={date:$('#cDate').value,periodId:$('#cPeriod').value||null,type:$('#cType').value,amount:num($('#cAmount').value),allocation:$('#cAlloc').value,vendor:$('#cVendor').value.trim(),description:$('#cDesc').value.trim(),createdAt:serverTimestamp(),createdBy:state.user.uid};await setDoc(ref,row);upsertLocal('costs',{id:ref.id,...row});closeModal();toast('تم حفظ المصروف');navigate('costs');};}

function renderPayments(){setTitle('الدفعات','سجّل الدفع، حتى لو كان المبلغ تحت الحساب.');const payments=state.data.payments||[];$('#app').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>الدفعات</h2><p>كل دفعة تظهر في كشف حساب الساكن وتخفض الرصيد.</p></div><button class="btn primary" id="addPayment">+ تسجيل دفعة</button></div><div class="table-wrap"><table class="table"><thead><tr><th>التاريخ</th><th>الساكن</th><th>المبلغ</th><th>الطريقة</th><th>الإيصال</th><th>ملاحظة</th></tr></thead><tbody>${payments.length?payments.slice().sort((a,b)=>String(b.paymentDate).localeCompare(String(a.paymentDate))).map(p=>`<tr><td>${fmtDate(p.paymentDate)}</td><td>${safe((state.data.subscribers||[]).find(s=>s.id===p.subscriberId)?.name||'—')}</td><td class="strong">${money(p.amount)}</td><td>${safe(p.method||'نقدي')}</td><td>${safe(p.receiptNumber||'—')}</td><td>${safe(p.note||'—')}</td></tr>`).join(''):`<tr><td colspan="6">${empty('لا توجد دفعات','سجّل أول دفعة من الزر أعلاه.')}</td></tr>`}</tbody></table></div></section>`;$('#addPayment').onclick=showPaymentForm;}
function showPaymentForm(){const subs=(state.data.subscribers||[]).filter(s=>s.active!==false);openModal(`<h2>تسجيل دفعة</h2><div class="form-grid"><div class="field full"><label>الساكن</label><select id="paySub">${subs.map(s=>`<option value="${s.id}">${safe(s.code)} — ${safe(s.name)}</option>`).join('')}</select></div><div class="field"><label>المبلغ</label><input id="payAmount" type="number" step="0.01" min="0.01"></div><div class="field"><label>التاريخ</label><input id="payDate" type="date" value="${dateNow()}"></div><div class="field"><label>طريقة الدفع</label><select id="payMethod"><option>نقدي</option><option>تحويل بنكي</option><option>أخرى</option></select></div><div class="field"><label>رقم الإيصال</label><input id="payReceipt"></div><div class="field full"><label>ملاحظة</label><input id="payNote"></div></div><div class="actions"><button class="btn primary" id="savePay">حفظ الدفعة</button><button class="btn light" id="cancelPay">إلغاء</button></div>`);$('#cancelPay').onclick=closeModal;$('#savePay').onclick=async()=>{const amount=num($('#payAmount').value);if(amount<=0){toast('أدخل مبلغًا صحيحًا','error');return;}const pRef=doc(orgCollection('payments'));const data={subscriberId:$('#paySub').value,amount,paymentDate:$('#payDate').value,method:$('#payMethod').value,receiptNumber:$('#payReceipt').value.trim(),note:$('#payNote').value.trim(),createdAt:serverTimestamp(),createdBy:state.user.uid};const batch=writeBatch(db);batch.set(pRef,data);batch.set(doc(orgCollection('ledger')),{subscriberId:data.subscriberId,credit:amount,debit:0,transactionType:'PAYMENT',description:`دفعة ${data.receiptNumber||''}`.trim(),paymentId:pRef.id,createdAt:serverTimestamp(),createdBy:state.user.uid});await batch.commit();upsertLocal('payments',{id:pRef.id,...data});upsertLocal('ledger',{subscriberId:data.subscriberId,credit:amount,debit:0,transactionType:'PAYMENT',description:`دفعة ${data.receiptNumber||''}`.trim(),paymentId:pRef.id});closeModal();toast('تم تسجيل الدفعة');navigate('payments');};}

function renderReports(){setTitle('التقارير','هنا فقط التنزيل والتقارير — الإعدادات موجودة بقسم مستقل.');const periods=[...(state.data.periods||[])].sort((a,b)=>String(b.startDate).localeCompare(String(a.startDate)));const subs=(state.data.subscribers||[]).map(subscriberRow);$('#app').innerHTML=`<section class="report-hero"><div><span class="crumb">التقارير والتصدير</span><h2>اختار التقرير واضغط تنزيل</h2><p>التصدير يعتمد على البيانات الموجودة الآن في Firebase.</p></div><div class="report-mark">XLSX</div></section><section class="report-grid"><div class="report-card"><div class="report-icon">♙</div><h3>السكان</h3><p>الأسماء والأكواد والوحدات والأرصدة.</p><button class="btn primary" id="rSubs">↓ تنزيل Excel</button></div><div class="report-card"><div class="report-icon">◫</div><h3>قراءات أسبوع</h3><p>السابقة والحالية والاستهلاك وقيمة المياه.</p><select id="rPeriod"><option value="">اختر الأسبوع</option>${periods.map(p=>`<option value="${p.id}">${safe(p.label)} — ${fmtDate(p.startDate)}</option>`).join('')}</select><button class="btn primary" id="rRead">↓ تنزيل Excel</button></div><div class="report-card"><div class="report-icon">₪</div><h3>الدفعات</h3><p>كل الدفعات المسجلة.</p><button class="btn primary" id="rPay">↓ تنزيل Excel</button></div><div class="report-card"><div class="report-icon">▤</div><h3>الأرصدة</h3><p>ملخص أرصدة السكان الحالية.</p><button class="btn primary" id="rBal">↓ تنزيل Excel</button></div></section>`;$('#rSubs').onclick=()=>exportSubscribers(subs);$('#rRead').onclick=()=>{const id=$('#rPeriod').value;if(!id){toast('اختر أسبوعًا أولًا','error');return;}exportPeriod(id)};$('#rPay').onclick=()=>exportPayments(state.data.payments||[]);$('#rBal').onclick=()=>exportBalances(subs);}

function exportXlsx(rows,sheet,file){if(window.XLSX){const wb=XLSX.utils.book_new();const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=Array(Math.max(6,Object.keys(rows[0]||{}).length)).fill({wch:20});XLSX.utils.book_append_sheet(wb,ws,sheet.slice(0,31));XLSX.writeFile(wb,file);toast('تم تنزيل ملف Excel');return;}const csv=[Object.keys(rows[0]||{}).join(','),...rows.map(r=>Object.values(r).map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href='data:text/csv;charset=utf-8,'+encodeURIComponent(csv);a.download=file.replace('.xlsx','.csv');a.click();toast('تم تنزيل CSV يفتح في Excel');}
function exportSubscribers(rows){exportXlsx(rows.map(s=>({الكود:s.code,الاسم:s.name,البناية:s.buildingName,الوحدة:s.unitCode,الهاتف:s.phone||'',الرصيد:s.balance||0})),'السكان','سكان_عمارة_الأمين.xlsx');}
function exportBalances(rows){exportXlsx(rows.map(s=>({الكود:s.code,الاسم:s.name,البناية:s.buildingName,الوحدة:s.unitCode,الرصيد:s.balance||0})),'الأرصدة','أرصدة_عمارة_الأمين.xlsx');}
function exportPayments(rows){exportXlsx(rows.map(p=>({التاريخ:p.paymentDate,الساكن:(state.data.subscribers||[]).find(s=>s.id===p.subscriberId)?.name||'',المبلغ:p.amount||0,الطريقة:p.method||'',رقم_الإيصال:p.receiptNumber||'',ملاحظة:p.note||''})),'الدفعات','دفعات_عمارة_الأمين.xlsx');}
function exportPeriod(pid){const p=(state.data.periods||[]).find(x=>x.id===pid);const rows=(state.data.readings||[]).filter(r=>r.periodId===pid).map(r=>{const m=(state.data.meters||[]).find(x=>x.id===r.meterId);const s=(state.data.subscribers||[]).find(x=>x.id===m?.subscriberId);return{الكود:s?.code||'',الاسم:s?.name||'',القراءة_السابقة:r.previousReading??'',القراءة_الحالية:r.currentReading??'',الاستهلاك:r.consumption??'',سعر_الكوب:r.unitPrice??p?.waterUnitPrice??'',قيمة_المياه:r.chargeAmount??'',الحالة:r.status||''}});exportXlsx(rows,'القراءات','قراءات_'+String(p?.label||pid).replace(/[^\w\u0600-\u06FF]+/g,'_')+'.xlsx');}

function renderSettings(){setTitle('الإعدادات','إدارة الحسابات والصلاحيات والحذف الآمن — بدون خلط مع التقارير.');const members=state.data.members||[];$('#app').innerHTML=`<section class="settings-grid"><div class="panel"><div class="panel-head"><div><h2>حسابك</h2><p>حساب Google المرتبط بالنظام.</p></div></div><div class="member"><div class="avatar">${safe((state.user.displayName||'م').slice(0,1))}</div><div class="member-main"><b>${safe(state.user.displayName||'—')}</b><span>${safe(state.user.email||'—')}</span></div>${statusBadge(state.profile.role)}</div><button class="btn light" id="logoutSettings" style="margin-top:12px">تسجيل الخروج</button></div><div class="panel"><div class="panel-head"><div><h2>المستخدمون</h2><p>أي حساب جديد يبدأ "بانتظار الموافقة" إلا المدير الرئيسي.</p></div></div><div class="member-list">${members.length?members.map(m=>`<div class="member"><div class="avatar">${safe((m.displayName||'م').slice(0,1))}</div><div class="member-main"><b>${safe(m.displayName||'—')}</b><span>${safe(m.email||'')}</span></div>${can('admin')?`<select data-role="${m.id}">${Object.entries(ROLES).filter(([k])=>k!=='pending').map(([k,v])=>`<option value="${k}" ${m.role===k?'selected':''}>${v}</option>`).join('')}</select>`:statusBadge(m.role)}</div>`).join(''):empty('لا يوجد مستخدمون','سيظهر الحساب بعد تسجيل الدخول.')}</div></div></section><section class="panel danger-zone"><h3>حذف أسبوع</h3><p>الحذف النهائي مخصص للمدير/المدير التنفيذي. إذا كان الأسبوع مغلقًا، يفضّل إبقاءه للأرشيف.</p><div class="danger-actions"><select id="deleteWeekSelect"><option value="">اختر أسبوعًا</option>${(state.data.periods||[]).map(p=>`<option value="${p.id}">${safe(p.label)} — ${fmtDate(p.startDate)}</option>`).join('')}</select><button class="btn danger" id="deleteWeek">حذف الأسبوع</button></div></section>`;$('#logoutSettings').onclick=()=>signOut(auth);$$('[data-role]').forEach(s=>s.onchange=()=>updateRole(s.dataset.role,s.value));$('#deleteWeek').onclick=()=>deleteWeek($('#deleteWeekSelect').value);}
async function updateRole(uid,role){if(!can('admin'))return;if(uid===state.user.uid&&role!=='admin'){toast('لا يمكنك تنزيل صلاحية المدير لنفسك.','error');return;}await updateDoc(orgDoc('members',uid),{role,updatedAt:serverTimestamp(),updatedBy:state.user.uid});upsertLocal('members',{id:uid,role});toast('تم تعديل الصلاحية');navigate('settings');}
async function deleteWeek(pid){if(!pid){toast('اختر أسبوعًا','error');return;}if(!can('admin','manager')){toast('ليست لديك صلاحية الحذف','error');return;}const p=state.data.periods.find(x=>x.id===pid);if(!confirm(`سيتم حذف ${p?.label||'الأسبوع'} مع قراءاته ومصاريفه المائية.\n\nهل أنت متأكد؟`))return;const batch=writeBatch(db);batch.delete(orgDoc('periods',pid));for(const r of (state.data.readings||[]).filter(x=>x.periodId===pid))batch.delete(orgDoc('readings',r.id));for(const c of (state.data.costs||[]).filter(x=>x.periodId===pid))batch.delete(orgDoc('costs',c.id));for(const t of (state.data.ledger||[]).filter(x=>x.periodId===pid&&t.transactionType==='WATER'))batch.delete(orgDoc('ledger',t.id));await batch.commit();toast('تم حذف الأسبوع');await navigate('settings',null,true);}

function openAccount(id){const s=(state.data.subscribers||[]).find(x=>x.id===id);if(!s)return;const row=subscriberRow(s);const ledger=(state.data.ledger||[]).filter(x=>x.subscriberId===id).slice().reverse();const readings=(state.data.readings||[]).filter(r=>{const m=(state.data.meters||[]).find(x=>x.id===r.meterId);return m?.subscriberId===id}).slice().reverse();openModal(`<div class="account-top"><div><span class="code">${safe(s.code)}</span><h2>${safe(s.name)}</h2><p>${safe(row.buildingName)} · ${safe(row.unitCode)} · ${safe(s.phone||'بدون هاتف')}</p></div><div class="balance-box"><span>الرصيد الحالي</span><b>${money(row.balance)}</b></div></div><div class="actions"><button class="btn gold" id="editAccount">تعديل بيانات الساكن</button><button class="btn primary" onclick="window.print()">طباعة / PDF</button></div><div class="account-section"><h3>آخر القراءات</h3><div class="table-wrap"><table class="table"><thead><tr><th>الأسبوع</th><th>السابقة</th><th>الحالية</th><th>الاستهلاك</th><th>القيمة</th></tr></thead><tbody>${readings.slice(0,12).map(r=>`<tr><td>${safe((state.data.periods||[]).find(p=>p.id===r.periodId)?.label||'—')}</td><td>${r.previousReading??'—'}</td><td>${r.currentReading??'—'}</td><td>${r.consumption==null?'—':fmt(r.consumption,3)}</td><td>${r.chargeAmount==null?'—':money(r.chargeAmount)}</td></tr>`).join('')||`<tr><td colspan="5">${empty('لا توجد قراءات','')}</td></tr>`}</tbody></table></div></div><div class="account-section"><h3>الحركات المالية</h3><div class="ledger">${ledger.slice(0,16).map(t=>`<div class="ledger-row"><div><b>${safe(t.description||t.transactionType||'حركة')}</b><span>${safe(t.transactionType||'')}</span></div><strong class="${num(t.credit)>0?'positive':''}">${num(t.credit)>0?'-':''}${money(Math.abs(num(t.debit)-num(t.credit)))}</strong></div>`).join('')||empty('لا توجد حركات','')}</div></div>`);$('#editAccount').onclick=()=>{closeModal();showSubscriberForm(id);};}

function showGuide(){
  const steps=[
    {title:'1) أول شيء: افتح الأسبوع',text:'كل أسبوع جديد يبدأ من زر «ابدأ أسبوعًا جديدًا». النظام يأخذ آخر قراءة موجودة ويضعها كقراءة سابقة حتى لا تعيد كتابتها من الصفر.',action:'showPeriodForm'},
    {title:'2) أدخل قراءات الماء',text:'من «قراءات الماء» اختر الأسبوع. أمام كل ساكن ستجد خانتين: السابقة والحالية. عدّل السابقة عند الحاجة، واكتب الحالية فقط. الاستهلاك يحسب تلقائيًا.',action:'navigateReadings'},
    {title:'3) سجّل المصاريف',text:'لو في مولد خارجي، سولار، صيانة أو مصروف طارئ: افتح «المصاريف» ثم أضف المصروف. لا تحسب المبلغ بنفسك إذا عندك كمية وسعر؛ البرنامج يحسبه.',action:'navigateCosts'},
    {title:'4) احسب وراجع',text:'بعد إدخال القراءات والمصاريف، راجع الأسبوع. إذا كانت القراءة الحالية أقل من السابقة سيظهر تنبيه بدل أن يعطيك حسابًا خاطئًا.',action:'navigateReadings'},
    {title:'5) سجّل الدفعات',text:'اضغط «تسجيل دفعة» من أعلى الشاشة، اختر الساكن، اكتب المبلغ وطريقة الدفع، ثم احفظ. سيُحدث البرنامج الرصيد تلقائيًا.',action:'showPaymentForm'},
    {title:'6) نزّل Excel',text:'اذهب إلى «التقارير». اختر نوع التقرير، وإذا كان التقرير أسبوعيًا اختر الأسبوع، ثم اضغط «تنزيل Excel». لا تحتاج أي رابط API.',action:'navigateReports'},
    {title:'7) تعديل السكان',text:'من «السكان» اضغط «تعديل» بجانب الشخص. يمكنك تعديل الاسم، الهاتف، الوحدة وغيرها، ويبقى تاريخ الحساب محفوظًا. للحذف استخدم الأرشفة أولًا.',action:'navigateSubscribers'},
  ];
  let i=0;
  const renderStep=()=>{
    const st=steps[i];
    openModal(`<div class="guide-shell practical-guide"><div class="guide-hero"><div class="guide-topline"><span class="guide-step-badge">شرح عملي</span><span class="guide-counter">${i+1} / ${steps.length}</span></div><h2>${st.title}</h2><p>${st.text}</p></div><div class="guide-demo"><div class="guide-demo-window"><div class="demo-title">عمارة الأمين</div><div class="demo-row"><span>ماذا أفعل الآن؟</span><b>${i<6?'نفّذ هذه الخطوة ثم انتقل للتالية':'بهذا تكون عرفت دورة العمل كاملة 🎉'}</b></div>${i===1?'<div class="demo-table"><div>السابقة <b>120000</b></div><div>الحالية <b class="demo-input">122500</b></div><div>الاستهلاك <b>2.500 كوب</b></div></div>':''}${i===4?'<div class="demo-table"><div>الساكن <b>اختر الاسم</b></div><div>المبلغ <b class="demo-input">100 ₪</b></div><div>الحالة <b>تم الحفظ ✓</b></div></div>':''}${i===5?'<div class="demo-table"><div>تقرير السكان</div><div>تقرير القراءات</div><div>⬇ تنزيل Excel</div></div>':''}</div></div><div class="guide-actions"><button class="btn light" id="guideClose">إغلاق</button><div class="guide-actions-right">${i>0?'<button class="btn light" id="guidePrev">السابق</button>':''}<button class="btn primary" id="guideNext">${i===steps.length-1?'انتهيت ✓':'التالي ←'}</button></div></div></div>`);
    $('#guideClose').onclick=closeModal;
    if($('#guidePrev')) $('#guidePrev').onclick=()=>{i--;renderStep();};
    $('#guideNext').onclick=()=>{
      const action=st.action;
      if(i===steps.length-1){closeModal();return;}
      if(action==='showPeriodForm'){closeModal();showPeriodForm();return;}
      if(action==='navigateReadings'){closeModal();navigate('readings');return;}
      if(action==='navigateCosts'){closeModal();navigate('costs');return;}
      if(action==='showPaymentForm'){closeModal();showPaymentForm();return;}
      if(action==='navigateReports'){closeModal();navigate('reports');return;}
      if(action==='navigateSubscribers'){closeModal();navigate('subscribers');return;}
      i++;renderStep();
    };
  };
  renderStep();
}

function renderPending(){setTitle('بانتظار الموافقة','حسابك مسجل، لكن المدير لم يمنحك صلاحية بعد.');$('#app').innerHTML=`<section class="panel" style="max-width:650px;margin:45px auto;text-align:center;padding:38px"><div style="font-size:38px">⌛</div><h2>باقي موافقة المدير</h2><p class="muted">تم تسجيل ${safe(state.user?.email||'حسابك')}. أخبر المدير بالموافقة على حسابك من الإعدادات.</p><button class="btn primary" onclick="location.reload()">تحديث الحالة</button></section>`;}

// Global events
$('#googleLogin')?.addEventListener('click',async()=>{try{await signInWithPopup(auth,provider);}catch(e){const box=$('#auth-error');box.textContent=e?.message||'تعذر تسجيل الدخول';box.classList.remove('hidden');}});
$('#logoutBtn')?.addEventListener('click',()=>signOut(auth));$('#refreshBtn')?.addEventListener('click',()=>navigate(state.view,state.periodId,true));$('#mobileMenu')?.addEventListener('click',()=>$('#sidebar')?.classList.toggle('open'));$('#quickPaymentBtn')?.addEventListener('click',showPaymentForm);$('#quickPeriod')?.addEventListener('click',showPeriodForm);$('#guideBtn')?.addEventListener('click',showGuide);$('#settingsBtn')?.addEventListener('click',()=>navigate('settings'));$('#modalClose')?.addEventListener('click',closeModal);$('#modal')?.addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal();});document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v)navigate(v.dataset.view);const a=e.target.closest('[data-account]');if(a)openAccount(a.dataset.account);const ed=e.target.closest('[data-edit-sub]');if(ed)showSubscriberForm(ed.dataset.editSub);const ar=e.target.closest('[data-archive-sub]');if(ar)archiveOrDelete(ar.dataset.archiveSub);});

onAuthStateChanged(auth,async user=>{state.user=user;$('#boot')?.classList.add('hidden');if(!user){$('#auth-screen')?.classList.remove('hidden');$('#app-shell')?.classList.add('hidden');return;}$('#auth-screen')?.classList.add('hidden');$('#app-shell')?.classList.remove('hidden');if($('#userName'))$('#userName').textContent=user.displayName||user.email||'المستخدم';if($('#userRole'))$('#userRole').textContent='جارٍ التحقق...';if($('#userAvatar'))$('#userAvatar').textContent=(user.displayName||user.email||'م').slice(0,1);try{state.profile=await ensureProfile();if($('#userRole'))$('#userRole').textContent=roleName(state.profile.role);if(state.profile.role==='admin')await ensureSetup();await loadData(true); await navigate('dashboard');}catch(e){console.error(e);$('#app').innerHTML=`<section class="panel" style="max-width:800px;margin:30px auto"><h2>ما قدرنا نحمل البيانات</h2><p class="muted">${safe(e?.message||'تحقق من Firestore Rules وAuthorized Domains وFirebase configuration.')}</p><details style="margin-top:10px"><summary>تفاصيل للمطور</summary><pre style="white-space:pre-wrap">${safe(e?.stack||'')}</pre></details></section>`;}});
