import {
  auth, provider, onAuthStateChanged, signInWithPopup, signInWithRedirect, getRedirectResult, signOut,
  db, orgCollection, orgDoc, getDoc, getDocs, setDoc, addDoc, updateDoc, deleteDoc,
  writeBatch, serverTimestamp, ADMIN_EMAILS
} from './firebase-init-v31.js';

const state={user:null,profile:null,tab:'dashboard',month:new Date().toISOString().slice(0,7),data:{},loaded:false,loading:false};
const COLS=['subscribers','members','fundGuardMonths','fundGuardPayments','fundGuardExpenses','solarReceipts','solarSales','fundOtherIncome','fundExpenses','fundConfig'];
const money=v=>`${new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Math.round(Number(v||0)))} ₪`;
const qty=v=>new Intl.NumberFormat('en-US',{maximumFractionDigits:3}).format(Number(v||0));
const num=v=>Number(v||0);
const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const ymd=v=>String(v||'').slice(0,10);
const fmtDate=v=>v?ymd(v).split('-').reverse().join('/'):'—';
const monthLabel=v=>{const [y,m]=String(v).split('-');const names=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];return y&&m?`${names[Number(m)-1]||m} ${y}`:v};
const canWrite=()=>['admin','manager','accountant'].includes(state.profile?.role);
const canDelete=()=>['admin','manager'].includes(state.profile?.role);
const isOwner=()=>ADMIN_EMAILS.map(x=>x.toLowerCase()).includes((state.user?.email||'').toLowerCase());

function toast(m,err=false){const t=document.querySelector('#toast');if(!t)return;t.textContent=m;t.className='toast '+(err?'error':'');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.className='toast hidden',3000)}
function openModal(html){document.querySelector('#modalBody').innerHTML=html;document.querySelector('#modal').classList.remove('hidden')}
function closeModal(){document.querySelector('#modal').classList.add('hidden');document.querySelector('#modalBody').innerHTML=''}
function setTitleForAuth(){document.querySelector('#boot')?.classList.add('hidden');}
function authError(e){const code=e?.code||'';return ({'auth/unauthorized-domain':'الدومين غير مصرح به في Firebase.','auth/operation-not-allowed':'تسجيل الدخول بحساب Google غير مفعّل.','auth/network-request-failed':'تعذر الاتصال بـ Firebase.','auth/popup-blocked':'تم حظر نافذة الدخول. سنستخدم التحويل بدلًا منها.'}[code]||e?.message||'تعذر تسجيل الدخول')}

async function ensureProfile(){
  const ref=orgDoc('members',state.user.uid), snap=await getDoc(ref);
  if(snap.exists()) return {id:snap.id,...snap.data()};
  const role=isOwner()?'admin':'pending';
  const data={displayName:state.user.displayName||'مستخدم',email:state.user.email||'',photoURL:state.user.photoURL||'',role,createdAt:serverTimestamp()};
  await setDoc(ref,data);return {id:ref.id,displayName:data.displayName,email:data.email,role};
}
async function load(){if(state.loaded||state.loading)return;state.loading=true;try{for(const c of COLS){const s=await getDocs(orgCollection(c));state.data[c]=s.docs.map(d=>({id:d.id,...d.data()}));}state.loaded=true;}finally{state.loading=false}}
async function saveDoc(c,id,data,merge=true){const ref=id?orgDoc(c,id):orgDoc(c,crypto.randomUUID());if(id&&merge)await updateDoc(ref,{...data,updatedAt:serverTimestamp(),updatedBy:state.user.uid});else await setDoc(ref,{id:ref.id,...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:state.user.uid});state.loaded=false;await load();}
async function addRow(c,data){const ref=orgDoc(c,crypto.randomUUID());await setDoc(ref,{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:state.user.uid});state.loaded=false;await load();return ref.id}
async function delRow(c,id,label){if(!canDelete()){toast('الحذف للمديرين فقط','error');return;}if(!confirm(`هل تريد حذف ${label||'هذا السجل'}؟`))return;await deleteDoc(orgDoc(c,id));state.loaded=false;await load();toast('تم الحذف');render()}
function rows(c){return state.data[c]||[]}
function subscribers(){return rows('subscribers').filter(s=>s.active!==false&&String(s.type||'').toLowerCase()!=='خارجي')}
function guardMonth(){return rows('fundGuardMonths').find(x=>x.month===state.month)}
function guardPayRows(){return rows('fundGuardPayments').filter(x=>x.month===state.month)}
function guardExpRows(){return rows('fundGuardExpenses').filter(x=>x.month===state.month)}
function solarRecRows(){return rows('solarReceipts').filter(x=>String(x.date||'').startsWith(state.month))}
function solarSaleRows(){return rows('solarSales').filter(x=>String(x.date||'').startsWith(state.month))}
function otherIncomeRows(){return rows('fundOtherIncome').filter(x=>String(x.date||'').startsWith(state.month))}
function fundExpRows(){return rows('fundExpenses').filter(x=>String(x.date||'').startsWith(state.month))}
function cleaningRows(){return guardExpRows().filter(x=>x.type==='cleaning')}
function salaryForMonth(){const gm=guardMonth();return num(gm?.salary||800)}
function guardFeeForMonth(){return num(guardMonth()?.feePerOwner||30)}
function guardEligibility(){const payMap=new Map(guardPayRows().map(x=>[x.subscriberId,x]));return subscribers().map(s=>{const x=payMap.get(s.id);const included=x?.included!==false;const paid=num(x?.paidAmount);const due=included?guardFeeForMonth():0;const status=paid<=0?'غير مدفوع':paid>=due?'مدفوع':'مدفوع جزئيًا';return {s,included,paid,due,status,x}})}
function guardSummary(){const items=guardEligibility();const required=items.reduce((a,x)=>a+x.due,0),collected=items.reduce((a,x)=>a+x.paid,0),otherIncome=otherIncomeRows().filter(x=>x.destination==='guard').reduce((a,x)=>a+num(x.amount),0),clean=cleaningRows().reduce((a,x)=>a+num(x.amount),0),salary=salaryForMonth(),net=collected+otherIncome-salary-clean;return {items,required,collected,otherIncome,uncollected:Math.max(0,required-collected),salary,clean,net,deficit:Math.max(0,-net)}}
function guardCumulativeBalance(){let v=0;for(const m of rows('fundGuardMonths')){const month=m.month;const items=rows('fundGuardPayments').filter(x=>x.month===month);const fee=num(m.feePerOwner||30);const collected=items.reduce((a,x)=>a+(x.included!==false?num(x.paidAmount):0),0);const clean=rows('fundGuardExpenses').filter(x=>x.month===month&&x.type==='cleaning').reduce((a,x)=>a+num(x.amount),0);v+=collected-num(m.salary||800)-clean;}v+=rows('fundOtherIncome').filter(x=>x.destination==='guard').reduce((a,x)=>a+num(x.amount),0);return v;}
function solarInventoryThrough(month){const end=`${month}-31`;const received=rows('solarReceipts').filter(x=>ymd(x.date)<=end).reduce((a,x)=>a+num(x.liters),0),sold=rows('solarSales').filter(x=>ymd(x.date)<=end).reduce((a,x)=>a+num(x.liters),0);return {received,sold,remaining:received-sold}}
function solarSummary(){const rec=solarRecRows(),sales=solarSaleRows();const received=rec.reduce((a,x)=>a+num(x.liters),0),sold=sales.reduce((a,x)=>a+num(x.liters),0),salesValue=sales.reduce((a,x)=>a+(x.totalAmount!=null?num(x.totalAmount):num(x.liters)*num(x.pricePerLiter)),0),transport=rec.reduce((a,x)=>a+Math.max(10,num(x.transportCost||10)),0),net=salesValue-transport,inv=solarInventoryThrough(state.month);return {rec,sales,received,sold,remaining:inv.remaining,salesValue,transport,net,stockReceived:inv.received,stockSold:inv.sold}}
function initialBalance(){return num(rows('fundConfig').find(x=>x.id==='main')?.initialBalance||0)}
function fundChangesBefore(date){const d=String(date).slice(0,10);let v=0;for(const r of rows('solarSales')){if(ymd(r.date)<d)v+=num(r.totalAmount!=null?r.totalAmount:num(r.liters)*num(r.pricePerLiter));}
  for(const r of rows('solarReceipts')){if(ymd(r.date)<d)v-=Math.max(10,num(r.transportCost||10));}
  for(const r of rows('fundOtherIncome')){if(ymd(r.date)<d&&r.destination==='fund')v+=num(r.amount)}
  for(const r of rows('fundExpenses')){if(ymd(r.date)<d)v-=num(r.amount)}
  return v;}
function fundBalanceAt(date){return initialBalance()+fundChangesBefore(`${date}T00:00:00`)}
function fundMonthlySummary(){const start=`${state.month}-01`;const opening=fundBalanceAt(start);const solar=solarSummary();const other=otherIncomeRows().filter(x=>x.destination==='fund').reduce((a,x)=>a+num(x.amount),0);const expenses=fundExpRows().reduce((a,x)=>a+num(x.amount),0);const closing=opening+solar.net+other-expenses;return {opening,solarNet:solar.net,other,expenses,closing}}
function lastMonths(){const set=new Set([...rows('fundGuardMonths').map(x=>x.month),...rows('solarReceipts').map(x=>String(x.date).slice(0,7)),...rows('solarSales').map(x=>String(x.date).slice(0,7)),...rows('fundOtherIncome').map(x=>String(x.date).slice(0,7)),...rows('fundExpenses').map(x=>String(x.date).slice(0,7))]);set.add(state.month);return [...set].filter(Boolean).sort().reverse()}

function header(title,sub,actions=''){return `<div class="panel-head"><div><h2>${title}</h2><p>${sub}</p></div><div class="actions">${actions}</div></div>`}
function renderDashboard(){const g=guardSummary(),s=solarSummary(),f=fundMonthlySummary();document.querySelector('#content').innerHTML=`
<section class="hero"><div class="eyebrow">${monthLabel(state.month)} · مستقل عن حسبة المياه</div><h2>صندوق العمارة والإيرادات</h2><p>كل ما هنا لا يدخل في سعر الكوب ولا في حسابات المياه. الصفحة مخصصة للصندوق، خدمة الحارس، السولار والإيرادات والمصروفات الأخرى.</p><div class="kpi-row"><div class="kpi"><span>المديونية/غير المحصل للحارس</span><b>${money(g.uncollected)}</b></div><div class="kpi"><span>صافي حساب الحارس</span><b>${money(g.net)}</b></div><div class="kpi"><span>صافي السولار للصندوق</span><b>${money(s.net)}</b></div><div class="kpi"><span>رصيد صندوق العمارة</span><b>${money(f.closing)}</b></div></div></section>
<section class="grid-4"><div class="stat"><div class="label">المطلوب لخدمة الحارس</div><div class="value">${money(g.required)}</div><div class="foot">عدد المشمولين × ${money(g.items.filter(x=>x.included).length?guardFeeForMonth():0).replace(' ₪',' ₪')}</div></div><div class="stat"><div class="label">المحصل من الحارس</div><div class="value">${money(g.collected)}</div><div class="foot">مدفوع + جزئي</div></div><div class="stat"><div class="label">راتب الحارس</div><div class="value">${money(g.salary)}</div><div class="foot">إعداد افتراضي 800 ويمكن تغييره</div></div><div class="stat"><div class="label">مصروفات النظافة</div><div class="value">${money(g.clean)}</div><div class="foot">أدوات ومواد</div></div>
<div class="stat"><div class="label">السولار المستلم</div><div class="value">${qty(s.received)}</div><div class="foot">لتر</div></div><div class="stat"><div class="label">السولار المباع</div><div class="value">${qty(s.sold)}</div><div class="foot">لتر</div></div><div class="stat"><div class="label">المتبقي</div><div class="value">${qty(s.remaining)}</div><div class="foot">لتر</div></div><div class="stat"><div class="label">مصروف نقل السولار</div><div class="value">${money(s.transport)}</div><div class="foot">الحد الأدنى 10 للعملية</div></div></section>
<section class="grid-2"><div class="panel">${header('خدمة الحارس','تحصيل شهري منفصل عن المياه.','<button class="btn primary" data-action="edit-guard-month">إعداد الشهر</button>')}<div class="summary-box"><div class="split"><span>إيراد الحارس المحصل</span><b>${money(g.collected)}</b></div><div class="split"><span>إيرادات أخرى للحارس</span><b>${money(g.otherIncome)}</b></div><div class="split"><span>راتب + نظافة</span><b>${money(g.salary+g.clean)}</b></div><div class="split"><span>صافي هذا الشهر</span><b>${money(g.net)}</b></div><div class="split"><span>رصيد حساب خدمات الحارس المتراكم</span><b>${money(guardCumulativeBalance())}</b></div>${g.deficit?`<div class="notice danger-note">يوجد عجز بمقدار ${money(g.deficit)}</div>`:''}</div></div><div class="panel">${header('صندوق العمارة','الرصيد الناتج من السولار والإيرادات الأخرى ناقص المصروفات.','<button class="btn soft" data-tab-go="fund">إدارة الصندوق</button>')}<div class="summary-box"><div class="split"><span>رصيد بداية الشهر</span><b>${money(f.opening)}</b></div><div class="split"><span>صافي السولار</span><b>${money(f.solarNet)}</b></div><div class="split"><span>إيرادات أخرى للصندوق</span><b>${money(f.other)}</b></div><div class="split"><span>مصروفات الصندوق</span><b>${money(f.expenses)}</b></div><div class="split"><span>الرصيد الحالي</span><b>${money(f.closing)}</b></div></div></div></section>`}

function renderGuard(){const g=guardSummary(),gm=guardMonth();document.querySelector('#content').innerHTML=`<section class="panel">${header('خدمة الحارس','المبلغ هنا شهري. يمكنك تحديد المبلغ للشخص الواحد واستثناء أشخاص محددين.','<button class="btn primary" data-action="edit-guard-month">إعداد شهر الحارس</button>')}<div class="grid-3"><div class="summary-box"><span class="muted">المبلغ على الشخص</span><b>${money(guardFeeForMonth())}</b></div><div class="summary-box"><span class="muted">عدد المشمولين</span><b>${g.items.filter(x=>x.included).length}</b></div><div class="summary-box"><span class="muted">الإيراد المطلوب</span><b>${money(g.required)}</b></div><div class="summary-box"><span class="muted">المحصل</span><b>${money(g.collected)}</b></div><div class="summary-box"><span class="muted">الراتب</span><b>${money(g.salary)}</b></div><div class="summary-box"><span class="muted">النظافة</span><b>${money(g.clean)}</b></div><div class="summary-box"><span class="muted">رصيد الحساب المتراكم</span><b>${money(guardCumulativeBalance())}</b></div></div></section>
<section class="panel">${header('مصاريف خدمة الحارس','راتب الحارس موجود في إعداد الشهر. هنا تسجل أدوات ومواد النظافة مثل القشاطات والمكانس والكلور.', '<button class="btn primary" data-action="add-guard-expense">+ مصروف نظافة</button>')}<div class="table-wrap"><table class="table"><thead><tr><th>التاريخ</th><th>المصروف</th><th>المبلغ</th><th>ملاحظات</th><th></th></tr></thead><tbody>${guardExpRows().map(r=>`<tr><td class="ltr">${fmtDate(r.date)}</td><td>${safe(r.description||'مواد نظافة')}</td><td>${money(r.amount)}</td><td>${r.attachmentUrl?`<a href="${safe(r.attachmentUrl)}" target="_blank" rel="noopener">فتح المرفق</a>`:'—'}<br>${safe(r.notes||'')}</td><td class="actions"><button class="btn small ghost" data-action="edit-guard-expense" data-id="${r.id}">تعديل</button><button class="btn small danger" data-action="delete" data-c="fundGuardExpenses" data-id="${r.id}">حذف</button></td></tr>`).join('')||`<tr><td colspan="5"><div class="empty"><b>لا توجد مصروفات نظافة</b></div></td></tr>`}</tbody></table></div></section>
<section class="panel">${header('دفعات المالكين','تحدد لكل مالك: مشمول/غير مشمول، والمبلغ المدفوع وحالته.','<button class="btn soft" data-action="save-guard-payments">حفظ دفعات الشهر</button>')}<div class="table-wrap"><table class="table"><thead><tr><th>الكود</th><th>الاسم</th><th>البناية</th><th>يشترك بالحارس</th><th>المطلوب</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th></tr></thead><tbody>${g.items.map(x=>`<tr data-owner-row="${x.s.id}"><td class="ltr">${safe(x.s.code||'')}</td><td>${safe(x.s.name||'')}</td><td>${safe(buildingName(x.s.unitId))}</td><td><input type="checkbox" data-guard-include="${x.s.id}" ${x.included?'checked':''}></td><td class="money">${money(x.due)}</td><td><input class="ltr" type="number" min="0" step="1" value="${num(x.paid)}" data-guard-paid="${x.s.id}"></td><td>${money(Math.max(0,x.due-x.paid))}</td><td>${x.status==='مدفوع'?'✅':x.status==='مدفوع جزئيًا'?'🟠':'⏳'} ${x.status}</td></tr>`).join('')}</tbody></table></div></section>`}

function renderSolar(){const s=solarSummary();document.querySelector('#content').innerHTML=`<section class="grid-2"><div class="panel">${header('استلام السولار','كل عملية مستقلة. تكلفة النقل لا تقل عن 10 ₪.','<button class="btn primary" data-action="add-solar-receipt">+ استلام سولار</button>')}<div class="summary-box"><div class="split"><span>المستلم</span><b>${qty(s.received)} لتر</b></div><div class="split"><span>مصروف النقل</span><b>${money(s.transport)}</b></div><div class="split"><span>المتبقي</span><b>${qty(s.remaining)} لتر</b></div>${s.remaining<0?'<div class="notice danger-note" style="margin-top:10px">تنبيه: الكمية المباعة أكبر من الكمية المستلمة المسجلة لهذا الشهر.</div>':''}</div><div class="table-wrap"><table class="table"><thead><tr><th>التاريخ</th><th>اللترات</th><th>المصدر</th><th>النقل</th><th>ملاحظات</th><th></th></tr></thead><tbody>${s.rec.length?s.rec.map(r=>`<tr><td class="ltr">${fmtDate(r.date)}</td><td class="ltr">${qty(r.liters)}</td><td>${safe(r.source||'—')}</td><td>${money(r.transportCost||10)}</td><td>${r.attachmentUrl?`<a href="${safe(r.attachmentUrl)}" target="_blank" rel="noopener">فتح المرفق</a>`:'—'}<br>${safe(r.notes||'')}</td><td class="actions"><button class="btn small ghost" data-action="edit-solar-receipt" data-id="${r.id}">تعديل</button><button class="btn small danger" data-action="delete" data-c="solarReceipts" data-id="${r.id}">حذف</button></td></tr>`).join(''):`<tr><td colspan="6"><div class="empty"><b>لا توجد عمليات</b><span>أضف أول استلام سولار للشهر.</span></div></td></tr>`}</tbody></table></div></div>
<div class="panel">${header('بيع السولار','سعر اللتر يختلف حسب السوق. يمكنك إدخال الإجمالي مباشرة.','<button class="btn primary" data-action="add-solar-sale">+ بيع سولار</button>')}<div class="summary-box"><div class="split"><span>الكمية المباعة</span><b>${qty(s.sold)} لتر</b></div><div class="split"><span>إجمالي المبيعات</span><b>${money(s.salesValue)}</b></div><div class="split"><span>صافي السولار للصندوق</span><b>${money(s.net)}</b></div></div><div class="table-wrap"><table class="table"><thead><tr><th>التاريخ</th><th>اللترات</th><th>سعر اللتر</th><th>الإجمالي</th><th>المشتري</th><th></th></tr></thead><tbody>${s.sales.length?s.sales.map(r=>`<tr><td class="ltr">${fmtDate(r.date)}</td><td class="ltr">${qty(r.liters)}</td><td>${money(r.pricePerLiter)}</td><td>${money(r.totalAmount!=null?r.totalAmount:num(r.liters)*num(r.pricePerLiter))}</td><td>${safe(r.buyer||'—')}</td><td class="actions"><button class="btn small ghost" data-action="edit-solar-sale" data-id="${r.id}">تعديل</button><button class="btn small danger" data-action="delete" data-c="solarSales" data-id="${r.id}">حذف</button></td></tr>`).join(''):`<tr><td colspan="6"><div class="empty"><b>لا توجد مبيعات</b><span>أضف عملية بيع سولار.</span></div></td></tr>`}</tbody></table></div></div></section>`}

function renderFund(){const f=fundMonthlySummary();document.querySelector('#content').innerHTML=`<section class="grid-4"><div class="stat"><div class="label">رصيد بداية الشهر</div><div class="value">${money(f.opening)}</div></div><div class="stat"><div class="label">صافي السولار الداخل</div><div class="value">${money(f.solarNet)}</div></div><div class="stat"><div class="label">إيرادات أخرى للصندوق</div><div class="value">${money(f.other)}</div></div><div class="stat"><div class="label">رصيد نهاية الشهر</div><div class="value">${money(f.closing)}</div></div></section>
<section class="grid-2"><div class="panel">${header('مصروفات صندوق العمارة','للطوارئ والصيانة والأصول والمرافق المشتركة.','<button class="btn primary" data-action="add-fund-expense">+ مصروف من الصندوق</button>')}<div class="table-wrap"><table class="table"><thead><tr><th>التاريخ</th><th>النوع</th><th>الوصف</th><th>المستفيد</th><th>المبلغ</th><th>المرفق/الملاحظات</th><th></th></tr></thead><tbody>${fundExpRows().map(r=>`<tr><td class="ltr">${fmtDate(r.date)}</td><td>${safe(r.type||'')}</td><td>${safe(r.description||'')}</td><td>${safe(r.payee||'')}</td><td>${money(r.amount)}</td><td class="actions"><button class="btn small ghost" data-action="edit-fund-expense" data-id="${r.id}">تعديل</button><button class="btn small danger" data-action="delete" data-c="fundExpenses" data-id="${r.id}">حذف</button></td></tr>`).join('')||`<tr><td colspan="7"><div class="empty"><b>لا توجد مصروفات</b></div></td></tr>`}</tbody></table></div></div><div class="panel">${header('الرصيد الافتتاحي','يستخدم كرصيد تأسيسي للصندوق.','<button class="btn soft" data-action="edit-opening">تعديل الرصيد الافتتاحي</button>')}<div class="notice">الرصيد الافتتاحي يخص الصندوق فقط، ولا يدخل في خدمة الحارس أو السولار أو حسبة المياه.</div><div class="summary-box" style="margin-top:10px"><div class="split"><span>الرصيد التأسيسي</span><b>${money(initialBalance())}</b></div></div></div></section>`}

function renderOther(){document.querySelector('#content').innerHTML=`<section class="panel">${header('إيرادات أخرى','إيراد مستقل لا علاقة له بحسبة المياه أو السولار. اختر أين يذهب.','<button class="btn primary" data-action="add-other-income">+ إضافة إيراد</button>')}<div class="table-wrap"><table class="table"><thead><tr><th>التاريخ</th><th>النوع/الاسم</th><th>المصدر</th><th>المبلغ</th><th>المكان</th><th>ملاحظات</th><th></th></tr></thead><tbody>${otherIncomeRows().map(r=>`<tr><td class="ltr">${fmtDate(r.date)}</td><td>${safe(r.name||'')}</td><td>${safe(r.source||'')}</td><td>${money(r.amount)}</td><td>${r.destination==='guard'?'حساب خدمات الحارس':'صندوق العمارة'}</td><td>${r.attachmentUrl?`<a href="${safe(r.attachmentUrl)}" target="_blank" rel="noopener">فتح المرفق</a>`:'—'}<br>${safe(r.notes||'')}</td><td class="actions"><button class="btn small ghost" data-action="edit-other-income" data-id="${r.id}">تعديل</button><button class="btn small danger" data-action="delete" data-c="fundOtherIncome" data-id="${r.id}">حذف</button></td></tr>`).join('')||`<tr><td colspan="8"><div class="empty"><b>لا توجد إيرادات أخرى</b></div></td></tr>`}</tbody></table></div></section>`}

function renderReports(){const g=guardSummary(),s=solarSummary(),f=fundMonthlySummary();document.querySelector('#content').innerHTML=`<section class="panel">${header('التقرير الشهري',`تقرير ${monthLabel(state.month)} كامل ومستقل عن حسبة المياه.`,'<button class="btn primary" data-action="download-report">تنزيل التقرير</button>')}<div class="report-grid"><div class="summary-box"><b>خدمة الحارس</b><p>المطلوب ${money(g.required)} · المحصل ${money(g.collected)} · المتبقي ${money(g.uncollected)} · راتب ${money(g.salary)} · نظافة ${money(g.clean)} · الصافي ${money(g.net)}</p></div><div class="summary-box"><b>السولار</b><p>عدد مرات الاستلام ${s.rec.length} · إجمالي المستلم ${qty(s.received)} لتر · المباع ${qty(s.sold)} لتر · المتبقي بنهاية الشهر ${qty(s.remaining)} لتر · قيمة المبيعات ${money(s.salesValue)} · النقل ${money(s.transport)} · صافي السولار للصندوق ${money(s.net)}</p></div><div class="summary-box"><b>صندوق العمارة</b><p>بداية ${money(f.opening)} · دخل السولار ${money(f.solarNet)} · إيرادات أخرى ${money(f.other)} · مصروفات ${money(f.expenses)} · نهاية ${money(f.closing)}</p></div></div></section>`}

function render(){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));({dashboard:renderDashboard,guard:renderGuard,solar:renderSolar,fund:renderFund,other:renderOther,reports:renderReports}[state.tab]||renderDashboard)()}

function guardForm(){const gm=guardMonth()||{month:state.month,feePerOwner:30,salary:800};openModal(`<h2>إعداد خدمة الحارس</h2><p class="muted">المبلغ هنا شهري، وليس أسبوعيًا.</p><form id="f"><div class="form-grid"><div class="field"><label>الشهر</label><input id="m" type="month" value="${gm.month}"></div><div class="field"><label>المبلغ على الشخص</label><input id="fee" type="number" min="0" step="1" value="${num(gm.feePerOwner||30)}"></div><div class="field"><label>راتب الحارس</label><input id="salary" type="number" min="0" step="1" value="${num(gm.salary||800)}"></div></div><div class="actions" style="margin-top:15px"><button class="btn primary">حفظ</button></div></form>`);document.querySelector('#f').onsubmit=async e=>{e.preventDefault();if(!canWrite())return toast('ليس لديك صلاحية التعديل','error');const id=gm.id||crypto.randomUUID();await saveDoc('fundGuardMonths',id,{month:document.querySelector('#m').value,feePerOwner:num(document.querySelector('#fee').value),salary:num(document.querySelector('#salary').value)});state.month=document.querySelector('#m').value;closeModal();render()}}
async function saveGuardPayments(){if(!canWrite())return toast('ليس لديك صلاحية التعديل','error');const ops=[];guardEligibility().forEach(x=>{const include=document.querySelector(`[data-guard-include="${x.s.id}"]`)?.checked??true;const paid=num(document.querySelector(`[data-guard-paid="${x.s.id}"]`)?.value);const existing=x.x?.id||crypto.randomUUID();ops.push(b=>b.set(orgDoc('fundGuardPayments',existing),{id:existing,month:state.month,subscriberId:x.s.id,included:include,paidAmount:include?paid:0,updatedAt:serverTimestamp(),updatedBy:state.user.uid,createdAt:x.x?.createdAt||serverTimestamp()}));});for(let i=0;i<ops.length;i+=400){const batch=writeBatch(db);ops.slice(i,i+400).forEach(fn=>fn(batch));await batch.commit()}state.loaded=false;await load();toast('تم حفظ دفعات الحارس');renderGuard()}
function guardExpenseForm(id){const r=id?rows('fundGuardExpenses').find(x=>x.id===id):null;openModal(`<h2>${r?'تعديل':'إضافة'} مصروف نظافة</h2><form id="f"><div class="form-grid"><div class="field"><label>التاريخ</label><input id="date" type="date" value="${r?.date||state.month+'-01'}"></div><div class="field"><label>اسم المصروف</label><input id="desc" value="${safe(r?.description||'') }" placeholder="مثال: قشاطة"></div><div class="field"><label>المبلغ</label><input id="amount" class="ltr" type="number" min="0" step="1" value="${num(r?.amount)}"></div><div class="field"><label>رابط صورة/إيصال (اختياري)</label><input id="attachmentUrl" class="ltr" type="url" placeholder="https://..." value="${safe(r?.attachmentUrl||'')}"></div><div class="field full"><label>ملاحظات</label><textarea id="notes">${safe(r?.notes||'')}</textarea></div></div><div class="actions" style="margin-top:15px"><button class="btn primary">حفظ</button></div></form>`);document.querySelector('#f').onsubmit=async e=>{e.preventDefault();if(!canWrite())return toast('ليس لديك صلاحية التعديل','error');const data={month:state.month,date:document.querySelector('#date').value,type:'cleaning',description:document.querySelector('#desc').value,amount:num(document.querySelector('#amount').value),notes:document.querySelector('#notes').value};if(id)await saveDoc('fundGuardExpenses',id,data);else await addRow('fundGuardExpenses',data);state.month=data.date.slice(0,7);closeModal();renderGuard()}}

function solarReceiptForm(id){const r=id?rows('solarReceipts').find(x=>x.id===id):null;openModal(`<h2>${r?'تعديل':'إضافة'} استلام سولار</h2><form id="f"><div class="form-grid"><div class="field"><label>التاريخ</label><input id="date" type="date" value="${r?.date||state.month+'-01'}"></div><div class="field"><label>الكمية باللتر</label><input id="liters" class="ltr" type="number" min="0" step="0.001" value="${num(r?.liters)}"></div><div class="field"><label>المصدر</label><input id="src" value="${safe(r?.source||'بلدية')}"></div><div class="field"><label>تكلفة النقل</label><input id="transport" class="ltr" type="number" min="10" step="1" value="${Math.max(10,num(r?.transportCost||10))}"></div><div class="field full"><label>ملاحظات</label><textarea id="notes">${safe(r?.notes||'')}</textarea></div></div><div class="actions" style="margin-top:15px"><button class="btn primary">حفظ</button></div></form>`);document.querySelector('#f').onsubmit=async e=>{e.preventDefault();const data={date:document.querySelector('#date').value,liters:num(document.querySelector('#liters').value),source:document.querySelector('#src').value,transportCost:Math.max(10,num(document.querySelector('#transport').value)),notes:document.querySelector('#notes').value};if(id)await saveDoc('solarReceipts',id,data);else await addRow('solarReceipts',data);state.month=data.date.slice(0,7);closeModal();renderSolar()}}
function solarSaleForm(id){const r=id?rows('solarSales').find(x=>x.id===id):null;openModal(`<h2>${r?'تعديل':'إضافة'} بيع سولار</h2><form id="f"><div class="form-grid"><div class="field"><label>التاريخ</label><input id="date" type="date" value="${r?.date||state.month+'-01'}"></div><div class="field"><label>اللترات المباعة</label><input id="liters" class="ltr" type="number" min="0" step="0.001" value="${num(r?.liters)}"></div><div class="field"><label>سعر اللتر</label><input id="price" class="ltr" type="number" min="0" step="1" value="${num(r?.pricePerLiter)}"></div><div class="field"><label>الإجمالي المباشر (اختياري)</label><input id="total" class="ltr" type="number" min="0" step="1" value="${r?.totalAmount!=null?num(r.totalAmount):''}"></div><div class="field"><label>اسم المشتري (اختياري)</label><input id="buyer" value="${safe(r?.buyer||'')}"></div><div class="field full"><label>ملاحظات</label><textarea id="notes">${safe(r?.notes||'')}</textarea></div></div><div class="notice">إذا أدخلت الإجمالي المباشر سيستخدمه البرنامج بدل (اللترات × سعر اللتر).</div><div class="actions" style="margin-top:15px"><button class="btn primary">حفظ</button></div></form>`);document.querySelector('#f').onsubmit=async e=>{e.preventDefault();const total=document.querySelector('#total').value.trim();const data={date:document.querySelector('#date').value,liters:num(document.querySelector('#liters').value),pricePerLiter:num(document.querySelector('#price').value),buyer:document.querySelector('#buyer').value,notes:document.querySelector('#notes').value};if(total)data.totalAmount=num(total);else delete data.totalAmount;if(id)await saveDoc('solarSales',id,data);else await addRow('solarSales',data);state.month=data.date.slice(0,7);closeModal();renderSolar()}}
function fundExpenseForm(id){const r=id?rows('fundExpenses').find(x=>x.id===id):null;openModal(`<h2>${r?'تعديل':'إضافة'} مصروف من الصندوق</h2><form id="f"><div class="form-grid"><div class="field"><label>التاريخ</label><input id="date" type="date" value="${r?.date||state.month+'-01'}"></div><div class="field"><label>نوع المصروف</label><select id="type"><option ${r?.type==='صيانة'?'selected':''}>صيانة</option><option ${r?.type==='طوارئ'?'selected':''}>طوارئ</option><option ${r?.type==='أصول'?'selected':''}>أصول العمارة</option><option ${r?.type==='مرافق'?'selected':''}>مرافق مشتركة</option><option ${r?.type==='أخرى'?'selected':''}>أخرى</option></select></div><div class="field"><label>المبلغ</label><input id="amount" class="ltr" type="number" min="0" step="1" value="${num(r?.amount)}"></div><div class="field"><label>المستفيد</label><input id="payee" value="${safe(r?.payee||'')}"></div><div class="field full"><label>الوصف</label><input id="desc" value="${safe(r?.description||'')}"></div><div class="field full"><label>ملاحظات</label><textarea id="notes">${safe(r?.notes||'')}</textarea></div></div><div class="actions" style="margin-top:15px"><button class="btn primary">حفظ</button></div></form>`);document.querySelector('#f').onsubmit=async e=>{e.preventDefault();const data={date:document.querySelector('#date').value,type:document.querySelector('#type').value,amount:num(document.querySelector('#amount').value),payee:document.querySelector('#payee').value,description:document.querySelector('#desc').value,attachmentUrl:document.querySelector('#attachmentUrl')?.value||'',notes:document.querySelector('#notes').value};if(id)await saveDoc('fundExpenses',id,data);else await addRow('fundExpenses',data);state.month=data.date.slice(0,7);closeModal();renderFund()}}
function otherIncomeForm(id){const r=id?rows('fundOtherIncome').find(x=>x.id===id):null;openModal(`<h2>${r?'تعديل':'إضافة'} إيراد آخر</h2><form id="f"><div class="form-grid"><div class="field"><label>التاريخ</label><input id="date" type="date" value="${r?.date||state.month+'-01'}"></div><div class="field"><label>اسم/نوع الإيراد</label><input id="name" value="${safe(r?.name||'')}"></div><div class="field"><label>المبلغ</label><input id="amount" class="ltr" type="number" min="0" step="1" value="${num(r?.amount)}"></div><div class="field"><label>مصدر الإيراد</label><input id="source" value="${safe(r?.source||'')}"></div><div class="field"><label>مكان إضافة الإيراد</label><select id="destination"><option value="fund" ${r?.destination!=='guard'?'selected':''}>صندوق العمارة</option><option value="guard" ${r?.destination==='guard'?'selected':''}>حساب خدمات الحارس</option></select></div><div class="field full"><label>ملاحظات</label><textarea id="notes">${safe(r?.notes||'')}</textarea></div></div><div class="actions" style="margin-top:15px"><button class="btn primary">حفظ</button></div></form>`);document.querySelector('#f').onsubmit=async e=>{e.preventDefault();const data={date:document.querySelector('#date').value,name:document.querySelector('#name').value,amount:num(document.querySelector('#amount').value),source:document.querySelector('#source').value,destination:document.querySelector('#destination').value,notes:document.querySelector('#notes').value};if(id)await saveDoc('fundOtherIncome',id,data);else await addRow('fundOtherIncome',data);state.month=data.date.slice(0,7);closeModal();renderOther()}}
function openingForm(){const cur=initialBalance();openModal(`<h2>الرصيد الافتتاحي للصندوق</h2><form id="f"><div class="field"><label>الرصيد</label><input id="amount" class="ltr" type="number" step="1" value="${cur}"></div><div class="actions" style="margin-top:15px"><button class="btn primary">حفظ</button></div></form>`);document.querySelector('#f').onsubmit=async e=>{e.preventDefault();if(!canWrite())return toast('ليس لديك صلاحية','error');await setDoc(orgDoc('fundConfig','main'),{id:'main',initialBalance:num(document.querySelector('#amount').value),updatedAt:serverTimestamp(),updatedBy:state.user.uid},{merge:true});state.loaded=false;await load();closeModal();renderFund()}}
function csvEscape(v){const t=String(v??'');return `"${t.replace(/"/g,'""')}"`}
function downloadReport(){const g=guardSummary(),s=solarSummary(),f=fundMonthlySummary();const lines=[];lines.push(['تقرير صندوق العمارة',monthLabel(state.month)]);lines.push([]);lines.push(['حساب خدمات الحارس']);lines.push(['عدد المشمولين',g.items.filter(x=>x.included).length]);lines.push(['المبلغ المطلوب',g.required]);lines.push(['المبلغ المحصل',g.collected]);lines.push(['المبلغ غير المحصل',g.uncollected]);lines.push(['راتب الحارس',g.salary]);lines.push(['مصروفات النظافة',g.clean]);lines.push(['إيرادات أخرى للحارس',g.otherIncome]);lines.push(['صافي الشهر',g.net]);lines.push(['الرصيد المتراكم لحساب الحارس',guardCumulativeBalance()]);lines.push([]);lines.push(['حساب السولار']);lines.push(['عدد مرات الاستلام',s.rec.length]);lines.push(['إجمالي المستلم باللتر',s.received]);lines.push(['إجمالي المباع باللتر',s.sold]);lines.push(['الكمية المتبقية باللتر',s.remaining]);lines.push(['إجمالي قيمة المبيعات',s.salesValue]);lines.push(['إجمالي نقل السولار',s.transport]);lines.push(['صافي السولار للصندوق',s.net]);lines.push([]);lines.push(['صندوق العمارة']);lines.push(['رصيد بداية الشهر',f.opening]);lines.push(['صافي السولار الداخل',f.solarNet]);lines.push(['إيرادات أخرى للصندوق',f.other]);lines.push(['مصروفات الصندوق',f.expenses]);lines.push(['رصيد نهاية الشهر',f.closing]);const csv='\uFEFF'+lines.map(r=>r.map(csvEscape).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`تقرير_صندوق_العمارة_${state.month}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('تم تنزيل التقرير بصيغة Excel/CSV')}

document.addEventListener('click',async e=>{const tab=e.target.closest('[data-tab]');if(tab){state.tab=tab.dataset.tab;render();return}const go=e.target.closest('[data-tab-go]');if(go){state.tab=go.dataset.tabGo;render();return}const a=e.target.closest('[data-action]');if(!a)return;const act=a.dataset.action;try{if(act==='edit-guard-month')guardForm();else if(act==='save-guard-payments')await saveGuardPayments();else if(act==='add-guard-expense')guardExpenseForm();else if(act==='edit-guard-expense')guardExpenseForm(a.dataset.id);else if(act==='add-solar-receipt')solarReceiptForm();else if(act==='edit-solar-receipt')solarReceiptForm(a.dataset.id);else if(act==='add-solar-sale')solarSaleForm();else if(act==='edit-solar-sale')solarSaleForm(a.dataset.id);else if(act==='add-fund-expense')fundExpenseForm();else if(act==='edit-fund-expense')fundExpenseForm(a.dataset.id);else if(act==='add-other-income')otherIncomeForm();else if(act==='edit-other-income')otherIncomeForm(a.dataset.id);else if(act==='edit-opening')openingForm();else if(act==='download-report')downloadReport();else if(act==='delete')await delRow(a.dataset.c,a.dataset.id,'السجل')}catch(err){console.error(err);toast(err?.message||'حدث خطأ أثناء العملية','error')}});
document.querySelector('#tabs').addEventListener('click',()=>{});
document.querySelector('#monthPicker').addEventListener('change',e=>{state.month=e.target.value;render()});
document.querySelector('#refreshBtn').onclick=async()=>{state.loaded=false;await load();render();toast('تم تحديث البيانات')};
document.querySelector('#logoutBtn').onclick=()=>signOut(auth);
document.querySelector('#modalClose').onclick=closeModal;
document.querySelector('#googleLogin').onclick=async()=>{const b=document.querySelector('#auth-error');b.classList.add('hidden');try{await signInWithPopup(auth,provider)}catch(e){try{await signInWithRedirect(auth,provider)}catch(re){b.textContent=authError(re);b.classList.remove('hidden')}}};
getRedirectResult(auth).catch(e=>{if(e){const b=document.querySelector('#auth-error');b.textContent=authError(e);b.classList.remove('hidden')}});

onAuthStateChanged(auth,async user=>{state.user=user;if(!user){document.querySelector('#auth-screen').classList.remove('hidden');document.querySelector('#app-shell').classList.add('hidden');setTitleForAuth();return}document.querySelector('#auth-screen').classList.add('hidden');document.querySelector('#app-shell').classList.remove('hidden');document.querySelector('#userName').textContent=user.displayName||user.email||'المستخدم';try{state.profile=await ensureProfile();const allowed=['admin','manager','accountant','operator','viewer'];if(state.profile.role==='pending'){document.querySelector('#content').innerHTML='<section class="panel" style="margin-top:30px"><h2>بانتظار موافقة المدير</h2><p class="muted">حسابك مسجل. اطلب من المدير إعطاءك صلاحية.</p></section>';document.querySelectorAll('.tab').forEach(x=>x.disabled=true);return}if(!allowed.includes(state.profile.role)&&!isOwner()){document.querySelector('#content').innerHTML='<section class="panel" style="margin-top:30px;text-align:center"><h2>هذه الصفحة للإدارة فقط</h2><p class="muted">لا تملك صلاحية الوصول إلى صندوق العمارة والإيرادات.</p><a class="btn primary" href="./index.html">العودة إلى إدارة الحسابات</a></section>';document.querySelectorAll('.tab').forEach(x=>x.disabled=true);return}await load();document.querySelector('#monthPicker').value=state.month;render()}catch(e){console.error(e);document.querySelector('#content').innerHTML=`<section class="panel"><h2>تعذر تحميل صندوق العمارة</h2><p class="muted">${safe(e?.message||'تحقق من صلاحيات Firebase.')}</p></section>`}});
