from pathlib import Path
p=Path('/mnt/data/v34/app-v33.js')
s=p.read_text(encoding='utf-8')
old="""function fundGuardSummary(){const items=fundGuardItems();const required=items.reduce((a,x)=>a+x.due,0),collected=items.reduce((a,x)=>a+x.paid,0),clean=fundRows('fundGuardExpenses').filter(x=>String(x.month||state.fundMonth)===state.fundMonth).reduce((a,x)=>a+Number(x.amount||0),0),other=fundRows('fundOtherIncome').filter(x=>String(x.date||'').startsWith(state.fundMonth)&&x.destination==='guard').reduce((a,x)=>a+Number(x.amount||0),0),salary=fundGuardSalary();return {items,required,collected,uncollected:Math.max(0,required-collected),clean,other,salary,net:collected+other-salary-clean}}"""
new="""function fundGuardSummary(){const items=fundGuardItems();const gm=fundGuardMonth();const required=Number(gm?.manualRevenue??0),collected=items.reduce((a,x)=>a+x.paid,0),clean=fundRows('fundGuardExpenses').filter(x=>String(x.month||state.fundMonth)===state.fundMonth).reduce((a,x)=>a+Number(x.amount||0),0),other=fundRows('fundOtherIncome').filter(x=>String(x.date||'').startsWith(state.fundMonth)&&x.destination==='guard').reduce((a,x)=>a+Number(x.amount||0),0),salary=fundGuardSalary();return {items,required,collected,uncollected:required>0?Math.max(0,required-collected):0,clean,other,salary,net:collected+other-salary-clean}}"""
if old not in s: raise SystemExit('summary pattern not found')
s=s.replace(old,new)
old2="""function fundGuardMonthForm(){const gm=fundGuardMonth();openModal(`<h2>${gm?'تعديل':'إعداد'} خدمة الحارس</h2><div class=\"form-grid\"><div class=\"field\"><label>الشهر</label><input id=\"fgMonth\" type=\"month\" value=\"${safe(state.fundMonth)}\"></div><div class=\"field\"><label>المبلغ على الشخص الواحد</label><input id=\"fgFee\" class=\"ltr\" type=\"number\" min=\"0\" step=\"1\" value=\"${fundGuardFee()}\"></div><div class=\"field\"><label>راتب الحارس</label><input id=\"fgSalary\" class=\"ltr\" type=\"number\" min=\"0\" step=\"1\" value=\"${fundGuardSalary()}\"></div></div><div class=\"actions\"><button class=\"btn primary\" id=\"saveFG\">حفظ</button></div>`);$('#saveFG').onclick=async()=>{if(!can('admin','manager','accountant')){toast('لا تملك صلاحية التعديل','error');return;}const month=$('#fgMonth').value||state.fundMonth;const data={id:gm?.id||`guard-${month}`,month,feePerOwner:num($('#fgFee').value),salary:num($('#fgSalary').value)};await saveDoc('fundGuardMonths',gm?.id||data.id,data,true);state.fundLoaded=false;state.fundMonth=month;await loadFundData(true);closeModal();render();}}"""
new2="""function fundGuardMonthForm(){const gm=fundGuardMonth();openModal(`<h2>${gm?'تعديل':'إعداد'} خدمة الحارس</h2><div class=\"form-grid\"><div class=\"field\"><label>الشهر</label><input id=\"fgMonth\" type=\"month\" value=\"${safe(state.fundMonth)}\"></div><div class=\"field\"><label>المبلغ على الشخص الواحد</label><input id=\"fgFee\" class=\"ltr\" type=\"number\" min=\"0\" step=\"1\" value=\"${fundGuardFee()}\"></div><div class=\"field\"><label>إجمالي إيراد خدمة الحارس المسجل يدويًا (اختياري)</label><input id=\"fgRevenue\" class=\"ltr\" type=\"number\" min=\"0\" step=\"1\" value=\"${Number(gm?.manualRevenue||0)}\"></div><div class=\"field\"><label>راتب الحارس</label><input id=\"fgSalary\" class=\"ltr\" type=\"number\" min=\"0\" step=\"1\" value=\"${fundGuardSalary()}\"></div></div><div class=\"hint\">لن يقوم النظام بحساب إجمالي الإيراد تلقائيًا من عدد السكان. أدخل الإيراد يدويًا هنا إذا أردت استخدامه كهدف تحصيل للشهر. مدفوعات السكان الفعلية تُسجل كل واحدة بشكل مستقل.</div><div class=\"actions\"><button class=\"btn primary\" id=\"saveFG\">حفظ</button></div>`);$('#saveFG').onclick=async()=>{if(!can('admin','manager','accountant')){toast('لا تملك صلاحية التعديل','error');return;}const month=$('#fgMonth').value||state.fundMonth;const data={id:gm?.id||`guard-${month}`,month,feePerOwner:num($('#fgFee').value),manualRevenue:num($('#fgRevenue').value),salary:num($('#fgSalary').value)};await saveDoc('fundGuardMonths',gm?.id||data.id,data,true);state.fundLoaded=false;state.fundMonth=month;await loadFundData(true);closeModal();render();}}"""
if old2 not in s: raise SystemExit('guard form pattern not found')
s=s.replace(old2,new2)
old3="""<div class=\"fund-kpi\"><span>المطلوب للحارس</span><b>${fundMoney(g.required)}</b></div><div class=\"fund-kpi\"><span>المحصل للحارس</span><b>${fundMoney(g.collected)}</b></div><div class=\"fund-kpi\"><span>صافي حساب الحارس</span><b>${fundMoney(g.net)}</b></div>"""
new3="""<div class=\"fund-kpi\"><span>الإيراد المحدد يدويًا</span><b>${g.required?fundMoney(g.required):'غير محدد'}</b></div><div class=\"fund-kpi\"><span>المحصل فعليًا</span><b>${fundMoney(g.collected)}</b></div><div class=\"fund-kpi\"><span>صافي حساب الحارس</span><b>${fundMoney(g.net)}</b></div>"""
if old3 not in s: raise SystemExit('overview kpi pattern not found')
s=s.replace(old3,new3)
old4="""<div><span>المطلوب</span><b>${fundMoney(g.required)}</b></div><div><span>المحصل</span><b>${fundMoney(g.collected)}</b></div><div><span>غير المحصل</span><b>${fundMoney(g.uncollected)}</b></div>"""
new4="""<div><span>الإيراد المحدد يدويًا</span><b>${g.required?fundMoney(g.required):'غير محدد'}</b></div><div><span>المحصل فعليًا</span><b>${fundMoney(g.collected)}</b></div><div><span>المتبقي من الهدف</span><b>${g.required?fundMoney(g.uncollected):'غير محدد'}</b></div>"""
if old4 not in s: raise SystemExit('overview lines pattern not found')
s=s.replace(old4,new4)
old5="""${header('خدمة الحارس','30 ₪ افتراضيًا لكل مشمول في الشهر، ويمكنك استثناء من لا يدفع.','<div class=\"panel-actions\"><button class=\"btn primary\" data-fund-action=\"guard-settings\">إعداد الشهر</button><button class=\"btn soft\" data-fund-action=\"save-guard\">حفظ الدفعات</button></div>')}"""
new5="""${header('خدمة الحارس','المبلغ على الشخص للتوزيع والمتابعة، أما إجمالي الإيراد الفعلي فتسجله أنت يدويًا. ويمكنك استثناء من لا يدفع.','<div class=\"panel-actions\"><button class=\"btn primary\" data-fund-action=\"guard-settings\">إعداد الشهر</button><button class=\"btn soft\" data-fund-action=\"save-guard\">حفظ الدفعات</button></div>')}"""
if old5 not in s: raise SystemExit('guard header pattern not found')
s=s.replace(old5,new5)
p.write_text(s,encoding='utf-8')
